
@hostname=localhost
@port=54011
@host = http://{{hostname}}:{{port}}
@contentType = application/json


###
GET {{host}}/api/greeting/foo

###
GET {{host}}/api/weatherforecast

### Failure: username
# URL과 Json 모두 대/소문자를 구분하지 않는다
POST {{host}}/api/user/register
content-type: application/json

{
    "username": "1234567890123456789012345678901@",
    "email": "x2",
    "password": "x3",
    "confirmPassword": "x4"
}

### Success
POST {{host}}/api/user/register
content-type: application/json

{
    "username": "1234567890",
    "email": "hello@world.com",
    "password": "x3",
    "confirmPassword": "x4"
}

# curl -X 'POST' \
#   'http://localhost:54011/api/User/Register' \
#   -H 'accept: */*' \
#   -H 'Content-Type: application/json' \
#   -d '{
#   "username": "1234567890",
#   "email": "hello@world.com",
#   "password": "x3",
#   "confirmPassword": "x4"
# }'



# ### Success
# GET {{host}}/api/users/foo

# ### Failure | Validation
# GET {{host}}/api/users/1234567890123456789012345678901

# ### Failure | Exception

# GET {{host}}/api/users/throw
