
@hostname=localhost
@port=54011
@host = http://{{hostname}}:{{port}}
@contentType = application/json


### 성공
DELETE {{host}}/api/user/permissions/OrderHeader_Read_Customer


### 성공
DELETE {{host}}/api/user/permissions/User_Read_Customer

### 실패
DELETE {{host}}/api/user/permissions/xyz

### 실패
DELETE {{host}}/api/user/permissions/4